name: ttk4260
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - notebook
  - casadi
  - pytorch
  - tqdm
  - xgboost
  - ipywidgets
