name: ttk4260
dependencies:
  - pip
  - python=3.6
  - numpy
  - matplotlib
  - scipy
  - pandas
  - scikit-learn
  - notebook
  - ipywidgets
  - tqdm
  - xgboost
  - ipykernel
  - pip:
    - scikit-image
    - casadi
    - torch
